development:
  adapter: mysql2
  encoding: utf8
  database: barterli_development
  pool: 5
  username: root
  password: root

test: &test
  adapter: mysql2
  encoding: utf8
  database: barterli_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: barterli_production
  pool: 5
  username: root
  password: root

cucumber:
  <<: *test